name:       koka
version:    2.1.7
github:     "koka-lang/koka"
license:    Apache-2.0
author:     Daan Leijen
maintainer: daan@microsoft.com

extra-source-files:
  - readme.md

description: Please see the README on GitHub at <https://github.com/koka-lang/koka#readme>

dependencies:
  - base >= 4.12 && < 5
  - array
  - bytestring
  - cond
  - containers
  - directory
  - mtl
  - parsec
  - process
  - text
  - time
  - haskeline

executables:
  koka:
    main: Main.hs
    # source-dirs: app
    # dependencies: koka
    other-extensions:
      - CPP
      - OverloadedStrings
    source-dirs:
      - src
      - src/Platform/cpp
    c-sources:
      - src/Platform/cpp/Platform/cconsole.c
    include-dirs:
      - src/Platform/cpp/Platform
    build-tools:
      - alex
    ghc-options:
      - -rtsopts
    cpp-options:
      - -DKOKA_MAIN="koka"      
      - -DKOKA_VARIANT="release"
      - -DKOKA_VERSION="2.1.7"
      # - -DREADLINE=1   # to avoid using Haskeline
    when:
      - condition: os(windows)
        cpp-options: -DWINDOWS
      - condition: os(darwin)
        cpp-options: -DDARWIN

tests:
  koka-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      # - koka
      - extra
      - filepath
      - hspec
      - hspec-core
      - process
      - regex-compat
      - json

